In [47]:
import torch

In [45]:
words = open("names.txt").read().splitlines()

n_words = len(words)

In [46]:
next_word_freq = {}

for w in words:
    chs = ["<S>"] + list(w) + ["</S>"]
    for ch1, ch2 in zip(chs, chs[1:]):
        k =(ch1,ch2)
        next_word_freq[k] = next_word_freq.get(k, 0) + 1


# sorted(next_word_freq, lambda x: len(x))
print(next_word_freq)

{('<S>', 'e'): 1531, ('e', 'm'): 769, ('m', 'm'): 168, ('m', 'a'): 2590, ('a', '</S>'): 6640, ('<S>', 'o'): 394, ('o', 'l'): 619, ('l', 'i'): 2480, ('i', 'v'): 269, ('v', 'i'): 911, ('i', 'a'): 2445, ('<S>', 'a'): 4410, ('a', 'v'): 834, ('v', 'a'): 642, ('<S>', 'i'): 591, ('i', 's'): 1316, ('s', 'a'): 1201, ('a', 'b'): 541, ('b', 'e'): 655, ('e', 'l'): 3248, ('l', 'l'): 1345, ('l', 'a'): 2623, ('<S>', 's'): 2055, ('s', 'o'): 531, ('o', 'p'): 95, ('p', 'h'): 204, ('h', 'i'): 729, ('<S>', 'c'): 1542, ('c', 'h'): 664, ('h', 'a'): 2244, ('a', 'r'): 3264, ('r', 'l'): 413, ('l', 'o'): 692, ('o', 't'): 118, ('t', 't'): 374, ('t', 'e'): 716, ('e', '</S>'): 3983, ('<S>', 'm'): 2538, ('m', 'i'): 1256, ('a', 'm'): 1634, ('m', 'e'): 818, ('<S>', 'h'): 874, ('r', 'p'): 14, ('p', 'e'): 197, ('e', 'r'): 1958, ('r', '</S>'): 1377, ('e', 'v'): 463, ('v', 'e'): 568, ('l', 'y'): 1588, ('y', 'n'): 1826, ('n', '</S>'): 6763, ('b', 'i'): 217, ('i', 'g'): 428, ('g', 'a'): 330, ('a', 'i'): 1650, ('i', 'l'): 1

In [73]:
t = torch.zeros((3,5), dtype=torch.int32)
t[2, 4] = 5
t

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 5]], dtype=torch.int32)

In [66]:
t[0, 0] += 1
t

tensor([[3, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [2, 0, 0, 0, 0]], dtype=torch.int32)

In [70]:
x = torch.ones((5,1), dtype=torch.int32)
x[0, 0] = 5
t @ x

tensor([[15],
        [ 5],
        [10]], dtype=torch.int32)